# Generated by Django 4.2 on 2024-10-31 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('passwords', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='password',
            options={'ordering': ('resource',), 'verbose_name': 'Пароль', 'verbose_name_plural': 'Пароли'},
        ),
        migrations.RemoveField(
            model_name='password',
            name='username',
        ),
        migrations.AddField(
            model_name='password',
            name='login',
            field=models.CharField(default='unknown', max_length=255, verbose_name='Логин на ресурсе'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='password',
            name='resource_icon',
            field=models.ImageField(blank=True, null=True, upload_to='resource_icons/', verbose_name='Иконка ресурса'),
        ),
        migrations.AlterField(
            model_name='password',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='password',
            name='resource',
            field=models.CharField(max_length=255, verbose_name='Ресурс'),
        ),
        migrations.AlterField(
            model_name='password',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AlterField(
            model_name='password',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_passwords', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Обновление'), ('delete', 'Удаление')], max_length=50, verbose_name='Действие')),
                ('target', models.CharField(max_length=255, verbose_name='Объект')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Временная метка')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Детали')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Журнал действий',
                'verbose_name_plural': 'Журналы действий',
                'ordering': ('-timestamp',),
            },
        ),
        migrations.AddField(
            model_name='password',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passwords', to='passwords.category', verbose_name='Категория'),
        ),
    ]
