# Generated by Django 4.2 on 2025-01-30 14:35

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to='avatars/', validators=[users.models.validate_image_size], verbose_name='Аватар'),
        ),
    ]
